
[project]
name = "mezha"
revision = "1.0"

[profiles.default]
STUB = { description = "Database connection string", required = false }

[profiles.development]
GEMINI_API_KEY = { description = "Gemini", required = false }
