#!/usr/bin/env bash
# Download the SecretSpec source matching the Go SDK, then stage its static ABI.
set -euo pipefail

version="v0.20.0"
source_sha256="e6484041c0c920a80c489b1fda0caf29c9b6ad6a7f6b906384dad6d64d96ba95"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cache_dir="$root/.cache/secretspec/$version"
source_dir="$cache_dir/source"
sdk_dir="$source_dir/secretspec-go"
goos="$(go env GOOS)"
goarch="$(go env GOARCH)"
archive="$sdk_dir/lib/libsecretspec_${goos}_${goarch}.a"
workfile="$root/.secretspec-static.work"

if [[ ! -f "$source_dir/Cargo.toml" ]]; then
  command -v curl >/dev/null || { echo "curl is required to download SecretSpec source" >&2; exit 1; }
  command -v tar >/dev/null || { echo "tar is required to unpack SecretSpec source" >&2; exit 1; }

  mkdir -p "$root/.cache"
  temp_dir="$(mktemp -d "$root/.cache/secretspec.XXXXXX")"
  trap 'rm -rf "$temp_dir"' EXIT
  archive_url="https://github.com/cachix/secretspec/releases/download/$version/source.tar.gz"
  curl --fail --location --silent --show-error --output "$temp_dir/source.tar.gz" "$archive_url"
  if command -v shasum >/dev/null; then
    actual="$(shasum -a 256 "$temp_dir/source.tar.gz" | awk '{print $1}')"
  elif command -v sha256sum >/dev/null; then
    actual="$(sha256sum "$temp_dir/source.tar.gz" | awk '{print $1}')"
  else
    echo "shasum or sha256sum is required to verify SecretSpec source" >&2
    exit 1
  fi
  [[ "$actual" == "$source_sha256" ]] || { echo "SecretSpec source checksum mismatch" >&2; exit 1; }

  rm -rf "$source_dir"
  mkdir -p "$source_dir"
  tar -xzf "$temp_dir/source.tar.gz" --strip-components=1 -C "$source_dir"
fi

if [[ ! -f "$archive" ]]; then
  command -v cargo >/dev/null || { echo "cargo is required to build SecretSpec's static library" >&2; exit 1; }
  bash "$sdk_dir/scripts/stage-staticlib.sh"
fi

cat > "$workfile" <<EOF
// Generated by scripts/stage-secretspec-static.sh; do not commit.
go 1.26.5

use (
	.
	./.cache/secretspec/$version/source/secretspec-go
)
EOF
